server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '^\[(?P<level>[A-Z]+)\] (?P<msg>.*)'
      - labels:
          level:
    relabel_configs:
      - source_labels: [__path__]
        regex: '/var/lib/docker/containers/([a-f0-9]{64})/.*'
        target_label: container_id
      - source_labels: [container_id]
        target_label: __meta_docker_container_id
      - source_labels: [__meta_docker_container_id]
        replacement: '$1'
        target_label: container_id
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_image]
        target_label: image
