services:
  web:
    image: nginx:latest
    container_name: devops_web_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      mynet:
        ipv4_address: 10.10.10.2
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops_server_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n0tDrivingDrunk118
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      mynet:
        aliases:
          - new_db
          - dev_db
        ipv4_address: 10.10.10.3

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28